### ISSUE TITLE
git.io

### ISSUE THREAD

**Issue by retnikt** [jstrieb/link-lock#2]
GitHub operates a URL shortener at https://git.io that only works on github.com and github.io pages, making its use a bit limited. However, this is a good use case for it. It maybe useful to add a note about this to the README.

**Comment by jstrieb** [comment]
This is incredibly helpful info, thank you! I will investigate further, and will likely replace the "Shorten URL" button in this and my URL pages project.

Would it be okay for me to mention you in the acknowledgements and credit you for pointing this out? If you consent to the mention, would you like me to link back to your GitHub, personal website, Twitter account, or something else?

**Comment by jstrieb** [comment]
Unfortunately, git.io was shut down today 😢 (<https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/>). As such, I will close this issue.

**Comment by akt5hh** [comment]
Hi

**Comment by aitdynamics** [comment]
hi Sent from Mail for Windows From: akt5hhSent: Thursday, January 13, 2022 7:22 PMTo: jstrieb/link-lockCc: SubscribedSubject: Re: [jstrieb/link-lock] git.io (#2) Hi—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by akt5hh** [comment]
Hi

**Comment by akt5hh** [comment]
Thanks sir
